[package]
name = "retina_rtsp"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rand = { workspace = true }
anyhow = { workspace = true }
cros-codecs = { workspace = true }
derive_builder = { workspace = true }
env_logger = { workspace = true }
hashbrown = { workspace = true }
log = { workspace = true }
mini-moka = { workspace = true }
parking_lot = { workspace = true }
retina = { workspace = true }
replaydb = { workspace = true }
savant_core = { workspace = true }
savant_services_common = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
twelf = { workspace = true }
url = { workspace = true }
futures = { workspace = true } 

