__all__ = ["version", "is_release_build", "register_handler", "unregister_handler"]

def version() -> str: ...
def is_release_build() -> bool: ...
def register_handler(element_name: str, h: object) -> None: ...
def unregister_handler(name: str) -> None: ...
