__all__ = ["version", "register_handler", "unregister_handler"]

def version() -> str: ...
def register_handler(element_name: str, h: object) -> None: ...
def unregister_handler(name: str) -> None: ...
