FROM ghcr.io/insight-platform/manylinux_2_28_x64:v0.0.4 as builder

COPY . .
ARG PYTHON_INTERPRETER
RUN bash /opt/docker/build-manylinux.sh
RUN rm -rf target

FROM alpine:3.18 as dist
COPY --from=builder /opt/dist /opt/dist
