FROM ghcr.io/insight-platform/savant_rust:v1.6.0 AS builder

RUN --mount=type=bind,source=.,target=/opt/savant-rs \
    pip install -r /opt/savant-rs/requirements.txt

# add rust path to PATH
ENV PATH="/root/.cargo/bin:$PATH"
ENV CARGO_TARGET_DIR=/tmp/build

RUN --mount=type=cache,target=/root/.cargo/registry \
    --mount=type=cache,target=/tmp/build \
    --mount=type=bind,rw,source=.,target=/opt/savant-rs \
    cd /opt/savant-rs && \
    make docs && \
    cp docs-artifact.tar ../
