FROM ghcr.io/insight-platform/manylinux_2_28_x64:v0.0.6 AS builder

COPY . .
ARG PYTHON_INTERPRETER
RUN make release
RUN rm -rf target

FROM alpine:3.18 AS dist
COPY --from=builder /opt/dist /opt/dist
