services:

  mediamtx-src:
    build:
      context: .
      dockerfile: Dockerfile.mediamtx
    restart: unless-stopped
    volumes:
      - ./sample_videos:/sample_videos
      - ./mediamtx.yml:/opt/mediamtx/mediamtx.yml

  mediamtx-re:
    build:
      context: .
      dockerfile: Dockerfile.mediamtx
    restart: unless-stopped
    volumes:
      - ./mediamtx_re.yml:/opt/mediamtx/mediamtx.yml
    depends_on:
      mediamtx-src:
        condition: service_started

  sync-rtsp-adapter:
    image: ghcr.io/insight-platform/savant-retina-rtsp-x86:1.0.5-rolling
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - ZMQ_ENDPOINT=pub+connect:ipc:///tmp/zmq-sockets/input-video.ipc
      - RTSP_LEFT_URI=rtsp://mediamtx-re:554/left
      - RTSP_RIGHT_URI=rtsp://mediamtx-re:554/right
    volumes:
      - ./configuration.json:/opt/etc/configuration.json
      - zmq_sockets:/tmp/zmq-sockets
    depends_on:
      mediamtx-re:
        condition: service_started
      stitching:
        condition: service_healthy

  stitching:
    image: ghcr.io/insight-platform/savant-deepstream:0.5.9-7.0
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ./src:/opt/savant/stitching
    command: stitching/module.yml
    environment:
      # - LOGLEVEL=debug
      - ZMQ_SRC_ENDPOINT=sub+bind:ipc:///tmp/zmq-sockets/input-video.ipc
      - ZMQ_SINK_ENDPOINT=dealer+bind:ipc:///tmp/zmq-sockets/output-video.ipc
      - METRICS_FRAME_PERIOD=10000
      - METRICS_TIME_PERIOD=60
      - DECODER_QUEUE_LENGTH=10
      - COMBINE_FRAMES_QUEUE_SIZE=60
      - WIDTH=1280
      - HEIGHT=720
      - BITRATE=16000000 # 64  Mbit/s
      - MAXBITRATE=16000000 # 64  Mbit/s
      - EGRESS_QUEUE_LENGTH=10
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  always-on-sink:
    image: ghcr.io/insight-platform/savant-adapters-deepstream:0.5.9-7.0
    restart: unless-stopped
    ports:
      - "888:888" # HLS
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ./stub_imgs:/stub_imgs
    environment:
      - ZMQ_ENDPOINT=router+connect:ipc:///tmp/zmq-sockets/output-video.ipc
      - SOURCE_ID=result
      - FRAMERATE=30/1
      - STUB_FILE_LOCATION=/stub_imgs/smpte100_1280x720.jpeg
      - DEV_MODE=True
    command: python -m adapters.ds.sinks.always_on_rtsp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    depends_on:
      sync-rtsp-adapter:
        condition: service_started

volumes:
  zmq_sockets:
