[package]
name = "replaydb"
description = "Replay Service"
license = "../LICENSE"
readme = "../README.md"

version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]

anyhow = { workspace = true }
bincode = { workspace = true }
derive_builder = { workspace = true }
env_logger = { workspace = true }
hashbrown = { workspace = true }
log = { workspace = true }
md-5 = { workspace = true }
mini-moka = { workspace = true }
uuid = { workspace = true }
parking_lot = { workspace = true }
rocksdb = { workspace = true }
savant_core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-timerfd = { workspace = true }
twelf = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

