from typing import Optional


class GstBuffer:
    @property
    def pts(self) -> Optional[int]: ...

    @property
    def dts(self) -> Optional[int]: ...

    @property
    def dts_or_pts(self) -> Optional[int]: ...

    @property
    def duration(self) -> Optional[int]: ...

    @property
    def flags(self) -> int: ...

    def unset_flags(self, flags: int) -> int: ...

    @property
    def maxsize(self) -> int: ...

    @property
    def n_memory(self) -> int: ...

    @property
    def offset(self) -> int: ...

    @property
    def offset_end(self) -> int: ...

    @property
    def size(self) -> int: ...

    @property
    def is_writable(self) -> bool: ...

    def copy(self) -> GstBuffer: ...

    def copy_deep(self) -> GstBuffer: ...

    def append(self, buf: GstBuffer) -> GstBuffer: ...
